### ISSUE TITLE
First meeting for 2017/2018 academic year

### ISSUE THREAD

**Issue by emielvanloon** [ScienceParkStudyGroup/studyGroup#2]
At this  first session, we would like to 
- present initial plans we have for the meet-ups during September - December 2017
- see if and when we can organise a software-carpentry and data-carpentry workshop in the winter
- present a short questionnaire to inventorize everyone's wishes for study/discussion-topics at the study group
- show two nice self-tuition courses for those who want to learn Python or R from scratch at their own pace in between the weekly meet-ups

location: [Cafe de Oerknal, Amsterdam Science Park](https://www.google.com/maps/place/Eetcaf%C3%A9+Oerknal/@52.355731,4.956279,18z/data=!4m5!3m4!1s0x0:0x12797808cd3ab881!8m2!3d52.3556349!4d4.9565365?hl=nl)

Time:  12 September, 17:00-18:00

**Comment by mgalland** [comment]
Hey Emiel, 
This programme would also nicely fit the next Study Group session!
Especially the part on the questionnaire and plans for a next workshop. 
Can we copy/paste most of it into a new post/issue?

**Comment by emielvanloon** [comment]
Hi Marc,


> Can we copy/paste most of it into a new post/issue?
Yes – excellent.

kind regards,
Emiel
