### ISSUE TITLE
Custom GTF file indexing

### ISSUE THREAD

**Issue by Fred-White94** [ScienceParkStudyGroup/studyGroup#30]
Hello World,

I have been attempting to use Kallisto to analyse genes and transposable elements in tandem.
This requires creating a custom gtf file to be used for kallisto index. It seems as though you can merge two gtf files as long as you are aware of the order and the transcript identifiers. Following this you can use the tophat command gtf_to_fasta to build the fasta file for the indexing. At this stage however it reorders many of the transcripts and sometimes makes the final output quite complicated to decipher in terms of target_id identification.

If anyone is aware of a better way of the custom index creation instead of just using single transcriptome files which are available online then please post it here.

Cheers

**Comment by mgalland** [comment]
Hello Fred. 
What I think you should do is:
1. Get the fasta file for genes (mRNAs) using the 'getfasta' command from bedtools for instance. [Find the command link here](https://bedtools.readthedocs.io/en/latest/content/tools/getfasta.html). You now have a "gene" fasta file.
2. Do the same for repeats. You get a "repeat" fasta file.
3. Combine the two fasta files with something like 'cat genes.fasta repeats.fasta >> reference.fasta'
4. Create the kallisto index with 'kallisto index --index=reference.index reference.fasta'  

Let me know how it goes!

**Comment by Fred-White94** [comment]
Hi Marc,

This definitely works on a sampled dataset - I haven't had time to scale up yet..

I would definitely recommend combining transcripts together at the fasta file stage rather than a as a gtf as this seems to cause problems when converting to fasta if there are transcripts that share a similar genomic location.

Thanks again
