### ISSUE TITLE
Simple plots with R by Joeri Jongbloets

### ISSUE THREAD

**Issue by mgalland** [ScienceParkStudyGroup/studyGroup#7]
# Description

In this lesson we repeat lesson #6, however this time we use R instead of Python. In short the lesson will teach you how to load data into R, how to manipulate the data and how to plot it.

We will use a powerful set of packages called [tidyverse](https://www.tidyverse.org) which includes all the basic packages you need for quick data loading, tidying, wrangling and plotting. In this lesson we will **not** discuss the basics of R language (but that will not stop us from using it).

**Check out the preparation guidelines below** 

# Time and Place
**Where:** Room D1.113, Science Park 904
**When:**  Tuesday, November 7th, 2017 at 17:00 PM

# Required Preparation

## Prior knowledge 
No prior knowledge required, but it never hurts to glance over [this](http://r4ds.had.co.nz/index.html).

## Data

* The 'train.csv' (training set) from [github](https://raw.githubusercontent.com/ScienceParkStudyGroup/studyGroup/gh-pages/lessons/20171107_Simple_plots_with_R_Joeri/train.csv) or [kaggle](https://www.kaggle.com/c/titanic/data)

## Software Dependencies

We will use R and RStudio.

- [To install R](http://cran-mirror.cs.uu.nl/)
- [To install RStudio](https://www.rstudio.com/products/rstudio/download/#download)

If possible, install tidyverse before the session:

1. Open RStudio (after you installed it)
2. Look at the lower right pane and click on the "Packages" tab
3. Click on the install button (just below the tabs)
4. In the dialog, enter "tidyverse"  (without the quotes) in the textbox and click Install.

## Materials

* The preview (or blank) document can be found [here](https://github.com/ScienceParkStudyGroup/studyGroup/blob/gh-pages/lessons/20171107_Simple_plots_with_R_Joeri/20171107_simple_plots_with_r_preview.Rmd)
* The complete document is available [here](https://github.com/ScienceParkStudyGroup/studyGroup/blob/gh-pages/lessons/20171107_Simple_plots_with_R_Joeri/20171107_simple_plots_with_r.Rmd)

**Comment by ajongbloets** [comment]
You can find the document that I made during the session [here](https://github.com/ScienceParkStudyGroup/studyGroup/blob/gh-pages/lessons/20171107_Simple_plots_with_R_Joeri/20171107_simple_plots_with_r_session.Rmd).
